server.port=8080

# MySQL Configuration (AWS RDS)
# Cambia esta línea en tu application.properties
spring.datasource.url=jdbc:mysql://fencepro-db.ctsqg6c8m2mc.eu-west-2.rds.amazonaws.com:3306/fencepro-db?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=velissanchez
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Security
app.security.jwt.secret=12345678901234567890123456789012
app.security.jwt.expirationMinutes=60

# API Base Path - COMENTADO PARA QUE CARGUE EL FRONTEND
# spring.mvc.servlet.path=/api

# PERFIL ACTIVO (prod para encriptación real en AWS)
spring.profiles.active=prod